logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

server:
  servlet:
    context-path: /api/v1
  port: 8080

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub


spring:
  datasource:
    url: jdbc:postgresql://project-db:5432/project
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

app:
  jwt:
    expirationS: 1800  # 30 min
    refreshExpirationS: 18000 # 5 h
  defaultSizePerPage:
    users: 10
    posts: 5
  defaultSortField:
    users: id
    posts: created
  defaultSortDirection:
    users: ASC
    posts: DESC
  picture:
    storage:
      path: /home/ilmira/pictures
